frontend/config/routes.rb
Capsule::Application.routes.draw do

  # auth and all sessions / connect controllers
  match '/auth/facebook/callback', to: 'omniauth#facebook'
  match '/auth/dailymotion/callback', to: 'omniauth#dailymotion'
  get "omni_session/connect"

  # for json request
  match '/capsuls_datas', to: 'capsuls#datas'

  # match '/:locale' => 'home#index'
  scope '(:locale)', constraints: { locale: /en|fr/ } do

    # all capsuls CRUD
    resources :capsuls

    #devise auth and sessions user
    devise_for :users, :path_names => { :sign_up => "register" }

    # any user profil exept current_user profil
    get "user/me"
    resources :user, :only => [:show]

    # search
    resources :search, :only => [:index]

    # root_path for /:locale
    root :to => 'home#index'
  end

end

frontend/app/models/capsul.rb
class Capsul < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags
  acts_as_gmappable :process_geocoding => false
  attr_accessible :description, :video, :longitude, :latitude

  after_create :append_tags

  private
  def append_tags
    self.description.split.each do |word|
      self.tags << Tag.find_or_create_by_tag(/^#(?<tag>\w+)$/.match(word)[:tag]) if word =~ /^#(?<tag>\w+$)/
    end
  end
end

frontend/app/controllers/capsuls_controller.rb
class CapsulsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index, :range]

  # GET /capsuls
  # GET /capsuls.json
  def index
    @capsuls = Capsul.order('created_at DESC').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @capsuls }
    end
  end

  # GET /capsuls_datas?from=int&limit=int&currentUser=bool
  def datas
    if params[:currentUser] and current_user
      user = User.find(current_user.id)
      @capsuls = user.capsuls.order('created_at DESC').limit(params[:limit]).offset(params[:from])
    else
      @capsuls = Capsul.order('created_at DESC').limit(params[:limit]).offset(params[:from])
    end
    respond_to do |format|
      format.json { render json: @capsuls }
      format.html # datas.html.erb
    end
  end

  # GET /capsuls/1
  # GET /capsuls/1.json
  def show
    @capsul = Capsul.find(params[:id])
    @json_map = nil
    if @capsul.latitude
      @json_map = @capsul.to_gmaps4rails
    end
    @owner = User.find(@capsul.user_id) if @capsul
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @capsul }
    end
  end

  # GET /capsuls/new
  # GET /capsuls/new.json
  def new
    @capsul = Capsul.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @capsul }
    end
  end

  # GET /capsuls/1/edit
  def edit
    @capsul = Capsul.find(params[:id])
  end

  # POST /capsuls
  # POST /capsuls.json
  def create
    user = User.find(current_user.id)
    @capsul = user.capsuls.new(params[:capsul])

    respond_to do |format|
      if @capsul.save
        format.html { redirect_to @capsul, notice: 'Capsul was successfully created.' }
        format.json { render json: @capsul, status: :created, location: @capsul }
      else
        format.html { render action: "new" }
        format.json { render json: @capsul.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /capsuls/1
  # PUT /capsuls/1.json
  def update
    @capsul = Capsul.find(params[:id])

    respond_to do |format|
      if @capsul.update_attributes(params[:capsul])
        format.html { redirect_to @capsul, notice: 'Capsul was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @capsul.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capsuls/1
  # DELETE /capsuls/1.json
  def destroy
    @capsul = Capsul.find(params[:id])
    @capsul.destroy

    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :no_content }
    end
  end
end

frontend/app/helpers/capsuls_helper.rb
module CapsulsHelper
end

frontend/app/views/capsuls/_form.html.haml
= form_for @capsul do |f|
  - if @capsul.errors.any?
    #error_explanation
      %h2= "#{pluralize(@capsul.errors.count, "error")} prohibited this capsul from being saved:"
      %ul
        - @capsul.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :video
    = f.text_field :video
  .field
    = f.label :longitude
    = f.text_field :longitude
  .field
    = f.label :latitude
    = f.text_field :latitude
  .actions
    = f.submit "#{t 'capsuls_link.save'}"

frontend/app/views/capsuls/datas.html.haml
- @capsuls.each do |capsul|
  %div{:class => "video-view"}
    %h5= link_to capsul.description, capsul_path(capsul)
    %iframe{:src => "http://www.dailymotion.com/embed/video/#{capsul.video}", :width => "620", :height => "400", :frameborder => "0"}

-# %table
-#   %tr
-#     %th Description
-#     %th Video
-#     %th User
-#     %th
-#     %th
-#     %th

-#   - @capsuls.each do |capsul|
-#     %tr
-#       %td= capsul.description
-#       %td= capsul.video
-#       - owner = User.find(capsul.user_id) if capsul
-#       %td= link_to owner.username, user_path(owner)
-#       %td= link_to 'Show', capsul_path(capsul)

frontend/app/views/capsuls/edit.html.haml
%h1 Editing capsul

= render 'form'

= link_to 'Show', @capsul
\|
= link_to 'Back', capsuls_path

frontend/app/views/capsuls/index.html.haml
%h1 Listing capsuls
- if current_user
  = link_to "#{t 'index.new_capsul'}", new_capsul_path
%br

%table
  %tr
    %th=t 'capsuls.description'
    %th=t 'capsuls.video'
    %th=t 'capsuls.user'
    %th
    %th
    %th

  - @capsuls.each do |capsul|
    %tr
      %td= capsul.description
      %td= capsul.video
      - owner = User.find(capsul.user_id) if capsul
      %td= link_to owner.username, user_path(owner)
      %td= link_to "#{t 'capsuls_link.show'}", capsul_path(capsul)

frontend/app/views/capsuls/new.html.haml
%h1 New capsul

= render 'form'

= link_to "#{t 'capsuls_link.back'}", capsuls_path

frontend/app/views/capsuls/show.html.haml
%p#notice= notice

- if current_user and @owner.id == current_user.id
  = link_to "#{t 'capsuls_link.edit'}", edit_capsul_path(@capsul)
  \|
= link_to 'Back', capsuls_path

%h3= @capsul.description

= link_to @owner.username, @owner

%iframe{:src => "http://www.dailymotion.com/embed/video/#{@capsul.video}", :width => "620", :height => "400", :frameborder => "0"}

- if @json_map
  .show_capsule_map_container
    = gmaps("map_options" => { "detect_location" => true, "center_on_user" => true, "zoom" => 10, "disableDefaultUI" => true, "width" => 100},"markers" => { "data" => @json_map})